services:
  - type: web
    name: telegram-ai-bot-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python readiness_check_render_ready.py
    envVars:
      - key: MONIQUE_TOKEN
        fromGroup: telegram-bot-env
      - key: COORDINATOR_TOKEN
        fromGroup: telegram-bot-env
      - key: TELEGRAM_CHAT_ID
        fromGroup: telegram-bot-env
